import {describe,expect,it,vi} from "vitest";
import {connectWallet,ensureStudionet,normalizeWalletError} from "../../lib/genlayer/wallet";

describe("generic injected Studionet wallet",()=>{
  it("requests accounts and never uses Snap RPC",async()=>{const calls:string[]=[];const provider:any={request:vi.fn(async({method}:any)=>{calls.push(method);if(method==="eth_requestAccounts")return ["0xabc"];if(method==="eth_chainId")return "0xf22f";throw new Error("unexpected")})};vi.stubGlobal("window",{ethereum:provider});vi.stubGlobal("localStorage",{setItem:vi.fn(),removeItem:vi.fn()});const result=await connectWallet();expect(result.address).toBe("0xabc");expect(calls).toContain("eth_requestAccounts");expect(calls.some(x=>x.includes("Snap")||x.includes("Snaps"))).toBe(false);vi.unstubAllGlobals();});
  it("switches and adds Studionet with standard EIP-1193 methods",async()=>{let chain="0x1";const methods:string[]=[];const provider:any={request:vi.fn(async({method}:any)=>{methods.push(method);if(method==="eth_chainId")return chain;if(method==="wallet_switchEthereumChain"){if(methods.filter(x=>x===method).length===1){const e:any=new Error("missing");e.code=4902;throw e;}chain="0xf22f";return null;}if(method==="wallet_addEthereumChain")return null;return null;})};await ensureStudionet(provider);expect(methods).toEqual(["eth_chainId","wallet_switchEthereumChain","wallet_addEthereumChain","wallet_switchEthereumChain","eth_chainId"]);});
  it("normalizes provider errors without exposing provider metadata",()=>{expect(normalizeWalletError({code:4001})).toBe("Transaction rejected in wallet.");expect(normalizeWalletError(new Error("unsupported chain switch"))).toContain("manually");expect(normalizeWalletError(new Error("rpc timeout"))).toContain("RPC");});
  it("distinguishes a rejected network switch",async()=>{const provider:any={request:vi.fn(async({method}:any)=>{if(method==="eth_chainId")return "0x1";const e:any=new Error("rejected switch");e.code=4001;throw e})};await expect(ensureStudionet(provider)).rejects.toThrow("Network switch rejected in wallet.");});
});
