import {createClient} from "genlayer-js"; import {studionet} from "genlayer-js/chains"; import {TransactionStatus,ExecutionResult} from "genlayer-js/types"; import {config} from "../config";
export type TxStage="AWAITING_SIGNATURE"|"SUBMITTED"|"CONSENSUS"|"ACCEPTED/FINALIZED"|"EXECUTION_CONFIRMED"|"USER_REJECTED"|"WRONG_NETWORK"|"CONTRACT_ERROR"|"CONSENSUS_FAILURE"|"EXECUTION_ERROR"|"RPC_UNAVAILABLE";
export const readClient=createClient({chain:studionet});
export function writeClient(address:string,provider:NonNullable<Window["ethereum"]>){return createClient({chain:studionet,account:address as `0x${string}`,provider});}
export async function readContract(address:string,functionName:string,args:any[]=[]){if(!address) throw new Error("Contract address is not configured in this deployment"); return readClient.readContract({address:address as `0x${string}`,functionName,args});}
export async function readEpoch(id:number){return readContract(config.rounds,"get_epoch",[id]);}
export function explorerTx(hash:string){return `${config.explorer}/tx/${hash}`;}
export type CanonicalCheck=()=>Promise<void>;
export type WriteServices={waitForFinalization?:(args:{hash:string})=>Promise<any>;};
export async function writeAndConfirm(client:any,address:string,functionName:string,args:any[],value=0n,onStage?:(s:TxStage)=>void,canonicalCheck?:CanonicalCheck,services:WriteServices={}){let hash:string|undefined;try{onStage?.("AWAITING_SIGNATURE"); await client.connect("studionet"); const write={address:address as `0x${string}`,functionName,args,value}; hash=await client.writeContract(write); if(!hash) throw new Error("Write did not return a transaction hash"); const submittedHash:string=hash; onStage?.("SUBMITTED"); onStage?.("CONSENSUS"); const receipt=services.waitForFinalization?await services.waitForFinalization({hash:submittedHash}):await readClient.waitForTransactionReceipt({hash:submittedHash as any,status:TransactionStatus.FINALIZED}); onStage?.("ACCEPTED/FINALIZED"); const execution=receipt.txExecutionResultName??receipt.execution_result; if(execution!==ExecutionResult.FINISHED_WITH_RETURN&&execution!=="SUCCESS"){onStage?.("EXECUTION_ERROR"); throw new Error(`Consensus finalized but contract execution failed: ${execution??"unknown"}`);} await canonicalCheck?.(); onStage?.("EXECUTION_CONFIRMED"); return {hash:submittedHash,receipt};}catch(e){const message=e instanceof Error?e.message:String(e); if(message.toLowerCase().includes("reject")){onStage?.("USER_REJECTED")} else if(message.toLowerCase().includes("consensus")){onStage?.("CONSENSUS_FAILURE")} else if(message.toLowerCase().includes("network")){onStage?.("WRONG_NETWORK")} else if(hash){onStage?.("EXECUTION_ERROR")} else {onStage?.("CONTRACT_ERROR")} throw e;}}
