"use client";
import Link from "next/link";
import {useEffect, useState} from "react";
import {config} from "@/lib/config";
import {readContract} from "@/lib/genlayer/client";
import {ContractAction} from "@/components/contract-action";
import {useWallet} from "@/components/wallet-provider";
import {formatGen} from "@/lib/genlayer/amounts";
type Claim = {id:number; epoch_id:number; claimant:string; title:string; type:string; status:string; impact_band:string; weight:number; reason:string; evidence:{source:number;excerpt:string}[]; challenge_status:string; challenge_used:boolean; attempts?:number};
export function ClaimState({id}:{id:number}) { const [claim,setClaim]=useState<Claim>(); const [epoch,setEpoch]=useState<any>(); const [pool,setPool]=useState<any>(); const [settlement,setSettlement]=useState<any>(); const [error,setError]=useState(""); const {address}=useWallet();
  const load=()=>readContract(config.rounds,"get_claim",[id]).then(async value=>{const c=value as Claim;setClaim(c);setEpoch(await readContract(config.rounds,"get_epoch",[c.epoch_id]));try{setPool(await readContract(config.pool,"get_pool",[c.epoch_id]));setSettlement(await readContract(config.pool,"get_claim_settlement",[c.epoch_id,id]))}catch{}}).catch(e=>setError(e instanceof Error?e.message:"Unable to read claim")); useEffect(()=>{void load()},[id,address]);
  if(error)return <p className="border-l-4 border-[var(--coral)] p-4">{error}</p>; if(!claim)return <p className="mono">Reading canonical claim state…</p>;
  const canChallenge=epoch?.status==="CHALLENGE"&&!claim.challenge_used&&claim.status!=="CHALLENGED"&&address?.toLowerCase()!==claim.claimant.toLowerCase(); const canEvaluate=epoch?.status==="EVALUATING"&&(claim.status==="SUBMITTED"||(claim.status==="INCONCLUSIVE"&&(claim.attempts||0)<3));
  return <div><div className="mono text-xs uppercase">Dossier {id} / {claim.status}</div><h1 className="serif mt-5 text-6xl leading-none md:text-8xl">{claim.title}</h1><div className="mt-10 grid gap-8 md:grid-cols-[1fr_.7fr]"><article><div className="plate p-7"><div className="mono text-xs">{claim.type} / {claim.status}</div><p className="mt-8 leading-7">{claim.reason||"No canonical reason recorded yet."}</p><div className="mt-8 border-t border-[var(--line)] pt-5"><div className="mono text-xs uppercase">Grounded evidence</div>{claim.evidence.length?claim.evidence.map((e,i)=><p className="mt-3 text-sm leading-6" key={i}>Source {e.source}: {e.excerpt}</p>):<p className="mt-3 text-sm">No evidence stored.</p>}</div></div><div className="mt-6 flex flex-wrap gap-3">{canEvaluate&&<ContractAction contract="rounds" method="evaluate_claim" args={[id]} label="Evaluate evidence" onComplete={load}/>} {canChallenge&&<Link className="button inline-block" href={`/challenge/${id}`}>Challenge the record</Link>}{claim.challenge_status==="PENDING"&&<ContractAction contract="rounds" method="resolve_challenge" args={[id]} label="Resolve challenge" onComplete={load}/>} {claim.status==="ELIGIBLE"&&pool?.status==="POOL_FINALIZED"&&<ContractAction contract="pool" method="claim" args={[claim.epoch_id,id]} label="Claim finalized GEN" onComplete={load} actionKey={`claim:${claim.epoch_id}:${id}`}/>}</div></article><aside className="border-l border-[var(--ink)] p-6"><div className="mono text-xs uppercase">Authoritative allocation</div><div className="serif mt-4 text-5xl">{claim.weight}</div><p className="mt-3 leading-7">Weight / {claim.impact_band}</p><p className="mt-5 text-sm">Challenge: {claim.challenge_status}</p><p className="mt-5 break-all text-xs">Claimant: {claim.claimant}</p>{pool&&<p className="mt-5 text-sm">Pool: {pool.status} / reserved {formatGen(BigInt(pool.claimed||0))}</p>}{settlement&&<div className="mt-5 border-t pt-5 text-sm"><p>Payout: {settlement.status||"NONE"}</p><p>Identity: {settlement.identity||"—"}</p><p>Recipient: {settlement.recipient||"—"}</p><p>Amount: {formatGen(BigInt(settlement.amount||0))}</p></div>}</aside></div></div>;
}
