"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {config} from "@/lib/config";
import {readContract} from "@/lib/genlayer/client";
import {ContractAction} from "@/components/contract-action";
import {formatGen,genToWei} from "@/lib/genlayer/amounts";
import {useWallet} from "@/components/wallet-provider";
type Epoch={title:string;scope:string;status:string;claim_count:number;total_weight:number;work_cutoff:number;claims_open:number;claims_close:number;challenge_close:number;min_sources:number};
const date=(n:number)=>new Date(n*1000).toISOString();
export function EpochState({id}:{id:number}){
 const [epoch,setEpoch]=useState<Epoch>(); const [pool,setPool]=useState<any>(); const [credit,setCredit]=useState<bigint>(0n); const [error,setError]=useState(""); const {address}=useWallet();
 const load=async()=>{try{setEpoch(await readContract(config.rounds,"get_epoch",[id]) as Epoch);try{const p=await readContract(config.pool,"get_pool",[id]);setPool(p);if(address)setCredit(BigInt(String(await readContract(config.pool,"get_funder_credit",[id,address]))))}catch{setPool(undefined)}}catch(e){setError(e instanceof Error?e.message:"Unable to read epoch")}};
 useEffect(()=>{void load()},[id,address]);
 if(error)return <p className="border-l-4 border-[var(--coral)] p-4">{error}</p>; if(!epoch)return <p className="mono">Reading canonical epoch state…</p>;
 const now=Math.floor(Date.now()/1000), openReady=epoch.status==="DRAFT"&&now>=Number(epoch.claims_open), beforeClose=now<Number(epoch.claims_close), settlementReady=Boolean(pool)&&(epoch.status==="FINALIZED"||epoch.status==="POOL_FINALIZED");
 const confirmFund=async()=>{const after:any=await readContract(config.pool,"get_pool",[id]);const afterCredit=address?BigInt(String(await readContract(config.pool,"get_funder_credit",[id,address]))):0n;if(BigInt(String(after.funded))!==BigInt(String(pool?.funded||0))+genToWei(1)||afterCredit!==credit+genToWei(1))throw new Error("Funding canonical readback mismatch");await load()};
 return <div><div className="flex flex-wrap justify-between gap-4 mono text-xs uppercase tracking-[.2em]"><span>Epoch {id} / {epoch.status}</span><span>Work cutoff {date(Number(epoch.work_cutoff))}</span></div><h1 className="serif mt-6 max-w-5xl text-6xl leading-none md:text-8xl">{epoch.title}</h1><p className="mt-8 max-w-2xl text-xl leading-8">{epoch.scope}</p><div className="mt-10 grid gap-4 md:grid-cols-4">{[["Status",epoch.status],["Claims",String(epoch.claim_count)],["Total weight",String(epoch.total_weight)],["Min sources",String(epoch.min_sources)]].map(([k,v])=><div className="plate p-5" key={k}><div className="mono text-xs uppercase">{k}</div><div className="serif mt-3 text-3xl">{v}</div></div>)}</div><div className="mt-10 grid gap-8 md:grid-cols-2"><div className="border-t-2 border-[var(--ink)] pt-5"><div className="mono text-xs uppercase">Contract configuration</div><p className="mt-4 break-all text-sm">Rounds: {config.rounds||"MISSING"}</p><p className="mt-2 break-all text-sm">Pool: {config.pool||"MISSING"}</p><p className="mt-2 text-sm">Pool funded: {formatGen(BigInt(pool?.funded||0))} / connected credit: {formatGen(credit)}</p><div className="mt-6 flex flex-wrap gap-3">{openReady&&<ContractAction contract="rounds" method="open_epoch" args={[id]} label="Open epoch" onComplete={load}/>} {epoch.status==="DRAFT"&&!openReady&&<span className="button opacity-60">Opens in {Math.max(0,Number(epoch.claims_open)-now)}s</span>} {(epoch.status==="CLAIMS_OPEN"||epoch.status==="EVALUATING")&&beforeClose&&<ContractAction contract="pool" method="fund" args={[id]} value={genToWei(1)} label="Fund pool with 1 GEN" onComplete={confirmFund}/>} {epoch.status==="FINALIZED"&&<ContractAction contract="pool" method="finalize_pool" args={[id]} label="Finalize pool" onComplete={load}/>}</div></div><div><div className="mono text-xs uppercase">Deadlines</div><div className="mt-4 space-y-3 text-sm"><p>Claims open: {date(Number(epoch.claims_open))}</p><p>Claims close: {date(Number(epoch.claims_close))}</p><p>Challenge close: {date(Number(epoch.challenge_close))}</p></div>{(epoch.status==="CLAIMS_OPEN"||epoch.status==="EVALUATING")&&beforeClose&&<Link className="button primary mt-7 inline-block" href={`/submit/${id}`}>Submit a claim</Link>}{settlementReady&&<Link className="button mt-7 ml-2 inline-block" href={`/settlement/${id}`}>View settlement</Link>}</div></div></div>;
}
