"use client";
import Link from "next/link";
import {useState} from "react";
import {Wallet, LogOut, Menu, X} from "lucide-react";
import {useWallet} from "@/components/wallet-provider";
import {shortAddress} from "@/lib/genlayer/wallet";

export function SiteHeader() {
  const {address,status,error,connect,switchToStudionet,disconnect,wallets,selectedWallet}=useWallet(); const [open,setOpen]=useState(false); const [chooser,setChooser]=useState(false); const startConnect=()=>wallets.length>1&&!selectedWallet?setChooser(true):void connect();
  return <header className="mx-auto max-w-7xl px-6 py-4 md:py-6"><div className="flex items-center justify-between"><Link href="/" className="serif text-3xl font-bold">Backfill<span className="text-[var(--coral)]">.</span></Link><nav className="hidden gap-7 text-sm font-bold md:flex"><Link href="/epochs">Epochs</Link><Link href="/me">My work</Link><Link href="/docs">Method</Link></nav><div className="flex items-center gap-2">{address&&<span aria-label="Connected wallet" className="button">{shortAddress(address)}</span>}{status==="WRONG_NETWORK"&&address&&<button className="button coral" onClick={()=>void switchToStudionet()}>Switch to Studionet</button>}{address&&<button aria-label="Disconnect wallet" className="button" onClick={disconnect}><LogOut size={16}/></button>}{!address&&<button className="button" disabled={status==="CONNECTING"} onClick={startConnect}><Wallet size={16}/>{status==="CONNECTING"?"Connecting…":"Connect wallet"}</button>}{selectedWallet&&address&&<button className="button" onClick={()=>setChooser(true)}>Change wallet</button>}<button aria-label="Open menu" className="button md:hidden" onClick={()=>setOpen(!open)}>{open?<X size={16}/>:<Menu size={16}/>}</button></div></div>{chooser&&<div className="mt-4 border border-[var(--ink)] bg-[var(--paper)] p-4"><div className="mono text-xs uppercase">Choose injected wallet</div><div className="mt-3 flex flex-wrap gap-2">{wallets.map(w=><button className="button" key={w.id} onClick={()=>{setChooser(false);void connect(w.id)}}>{w.name}</button>)}</div></div>}{(error||status==="WRONG_NETWORK")&&<div className="mt-3 border-l-4 border-[var(--coral)] px-3 py-2 text-sm">{error||"Switch to GenLayer Studionet (61999)."}</div>}{open&&<nav className="mt-5 grid gap-3 border-t border-[var(--ink)]/15 pt-4 text-sm font-bold md:hidden"><Link onClick={()=>setOpen(false)} href="/epochs">Epochs</Link><Link onClick={()=>setOpen(false)} href="/me">My work</Link><Link onClick={()=>setOpen(false)} href="/docs">Method</Link></nav>}</header>;
}
