"use client";
import {createContext,useContext,useEffect,useMemo,useState} from "react";
import {config} from "@/lib/config";
import {connectWallet,disconnectWallet,ensureStudionet,getInjectedProvider,normalizeWalletError,type EIP1193Provider} from "@/lib/genlayer/wallet";
type WalletStatus="DISCONNECTED"|"CONNECTING"|"CONNECTED"|"WRONG_NETWORK";
type WalletContextValue={provider?:EIP1193Provider;address:string;chainId:string;status:WalletStatus;error:string;connect:()=>Promise<string>;switchToStudionet:()=>Promise<void>;disconnect:()=>void};
const WalletContext=createContext<WalletContextValue|undefined>(undefined);const expected=`0x${config.chainId.toString(16)}`;
export function WalletProvider({children}:{children:React.ReactNode}){const [provider,setProvider]=useState<EIP1193Provider>();const [address,setAddress]=useState("");const [chainId,setChainId]=useState("");const [status,setStatus]=useState<WalletStatus>("DISCONNECTED");const [error,setError]=useState("");
useEffect(()=>{let active=true;getInjectedProvider().then(async p=>{if(!active)return;setProvider(p);const [accounts,chain]=await Promise.all([p.request({method:"eth_accounts"}),p.request({method:"eth_chainId"})]);if(!active)return;const a=(accounts as string[])[0]||"";const c=String(chain);setAddress(a);setChainId(c);setStatus(a?(c.toLowerCase()===expected?"CONNECTED":"WRONG_NETWORK"):"DISCONNECTED")}).catch(()=>undefined);return()=>{active=false}},[]);
useEffect(()=>{if(!provider)return;const accountsChanged=(value:unknown)=>{const a=(value as string[])[0]||"";setAddress(a);setStatus(a?(chainId.toLowerCase()===expected?"CONNECTED":"WRONG_NETWORK"):"DISCONNECTED");if(a)localStorage.setItem("backfill.account",a);else disconnectWallet()};const chainChanged=(value:unknown)=>{const c=String(value);setChainId(c);setStatus(address?(c.toLowerCase()===expected?"CONNECTED":"WRONG_NETWORK"):"DISCONNECTED")};const disconnected=()=>{setAddress("");setChainId("");setStatus("DISCONNECTED");disconnectWallet()};provider.on?.("accountsChanged",accountsChanged);provider.on?.("chainChanged",chainChanged);provider.on?.("disconnect",disconnected);return()=>{provider.removeListener?.("accountsChanged",accountsChanged);provider.removeListener?.("chainChanged",chainChanged);provider.removeListener?.("disconnect",disconnected)}},[provider,address,chainId]);
const value=useMemo<WalletContextValue>(()=>({provider,address,chainId,status,error,connect:async()=>{setStatus("CONNECTING");setError("");try{const result=await connectWallet();setProvider(result.provider);setAddress(result.address);const c=String(await result.provider.request({method:"eth_chainId"}));setChainId(c);setStatus(c.toLowerCase()===expected?"CONNECTED":"WRONG_NETWORK");return result.address}catch(e){setError(normalizeWalletError(e));setStatus(address?"WRONG_NETWORK":"DISCONNECTED");throw e}},switchToStudionet:async()=>{if(!provider){setError("No injected wallet provider detected.");return}setStatus("CONNECTING");setError("");try{await ensureStudionet(provider);const c=String(await provider.request({method:"eth_chainId"}));if(c.toLowerCase()!==expected)throw new Error("Wallet is not on GenLayer Studionet (61999).");setChainId(c);setStatus("CONNECTED")}catch(e){setError(normalizeWalletError(e));setStatus("WRONG_NETWORK")}},disconnect:()=>{disconnectWallet();setAddress("");setChainId("");setStatus("DISCONNECTED")}}),[provider,address,chainId,status,error]);return <WalletContext.Provider value={value}>{children}</WalletContext.Provider>}
export function useWallet(){const value=useContext(WalletContext);if(!value)throw new Error("useWallet must be used inside WalletProvider");return value}
