"use client";
import {useEffect, useState} from "react";
import Link from "next/link";
import {config} from "@/lib/config";
import {readContract} from "@/lib/genlayer/client";
import {shortAddress} from "@/lib/genlayer/wallet";

export default function Me() { const [account, setAccount] = useState(""); const [claims, setClaims] = useState<any[]>([]); const [error, setError] = useState("");
  useEffect(() => { const load = async () => { const a = localStorage.getItem("backfill.account") || ""; setAccount(a); if (!a) return; const count = Number(await readContract(config.rounds, "get_epoch_count")); const rows: any[] = []; for (let epochId = 1; epochId <= count; epochId++) { const epoch: any = await readContract(config.rounds, "get_epoch", [epochId]); for (let index = 0; index < Number(epoch.claim_count); index++) { const claimId = Number(await readContract(config.rounds, "get_epoch_claim_id", [epochId, index])); const claim: any = await readContract(config.rounds, "get_claim", [claimId]); if (String(claim.claimant).toLowerCase() === a.toLowerCase()) rows.push(claim); } } setClaims(rows); }; load().catch(e => setError(e instanceof Error ? e.message : "Unable to read wallet claims")); }, []);
  return <div className="mx-auto max-w-5xl px-6 pb-24 pt-14"><div className="mono text-xs uppercase">Your work / wallet-scoped</div><h1 className="serif mt-5 text-7xl">The short list.</h1>{account ? <><p className="mt-7 text-lg">Connected account: <span className="mono">{shortAddress(account)}</span></p>{error && <p className="mt-8 border-l-4 border-[var(--coral)] p-4">{error}</p>}<div className="mt-12 space-y-4">{claims.length ? claims.map(c => <Link className="plate block p-5" href={`/claim/${c.id}`} key={c.id}><div className="mono text-xs">CLAIM {c.id} / {c.status}</div><div className="serif mt-3 text-2xl">{c.title}</div><p className="mt-2">Weight {c.weight} / {c.impact_band}</p></Link>) : <p className="mono">No claims found for this wallet in the configured deployment.</p>}</div></> : <div className="mt-14 border-y border-[var(--ink)] py-8"><p className="serif text-3xl">Connect a Studionet wallet to read authoritative claims.</p><Link href="/epochs" className="button mt-7 inline-block">Browse the ledger</Link></div>}</div>;
}
