"use client";
import Link from "next/link";
import {useEffect, useState} from "react";
import {useParams} from "next/navigation";
import {z} from "zod";
import {config} from "@/lib/config";
import {normalizeWalletError} from "@/lib/genlayer/wallet";
import {useWallet} from "@/components/wallet-provider";
import {readContract, writeClient, writeAndConfirm, type TxStage} from "@/lib/genlayer/client";
import {TxLifecycle} from "@/components/tx-lifecycle";
const schema = z.object({reason: z.enum(["wrong attribution", "work after cutoff", "duplicated contribution", "out of scope", "overstated impact"]), url: z.string().url().startsWith("https://").max(320)});
export default function Challenge() { const {id} = useParams<{id: string}>(); const [claim, setClaim] = useState<any>(); const [epoch, setEpoch] = useState<any>(); const [stage, setStage] = useState<TxStage>(); const [error, setError] = useState(""); const {address,ensureWriteReady}=useWallet();
  useEffect(() => { readContract(config.rounds, "get_claim", [Number(id)]).then(async value => { const c = value as any; setClaim(c); setEpoch(await readContract(config.rounds, "get_epoch", [Number(c.epoch_id)])); }).catch(e => setError(e instanceof Error ? e.message : "Unable to read claim")); }, [id]);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const p = schema.safeParse(Object.fromEntries(new FormData(event.currentTarget))); if (!p.success || !claim || !epoch) { setError("Choose a valid reason and HTTPS counter-evidence URL."); return; } try { const {address:a,provider} = await ensureWriteReady(); if (epoch.status !== "CHALLENGE" || claim.challenge_used || claim.status === "CHALLENGED" || claim.claimant.toLowerCase() === a.toLowerCase() || Math.floor(Date.now() / 1000) >= Number(epoch.challenge_close)) throw new Error("The contract does not currently permit this challenge"); await writeAndConfirm(writeClient(a, provider), config.rounds, "challenge_claim", [Number(id), p.data.reason, p.data.url], 0n, setStage, async () => { const after: any = await readContract(config.rounds, "get_claim", [Number(id)]); if (after.status !== "CHALLENGED" || after.challenge_status !== "PENDING") throw new Error("Challenge canonical readback mismatch"); setClaim(after); }, {actionKey: `challenge:${id}:${a.toLowerCase()}`, contract: config.rounds}); } catch (e) { setError(normalizeWalletError(e)); } }
  const permitted = Boolean(address)&&claim && epoch && epoch.status === "CHALLENGE" && claim.status !== "CHALLENGED" && !claim.challenge_used && address.toLowerCase() !== claim.claimant.toLowerCase() && Math.floor(Date.now() / 1000) < Number(epoch.challenge_close);
  return <div className="mx-auto max-w-3xl px-6 pb-24 pt-14"><div className="mono text-xs uppercase">Dossier {id} / bounded challenge</div><h1 className="serif mt-5 text-7xl leading-none">Add counter-evidence.</h1>{error && <p className="mt-8 border-l-4 border-[var(--coral)] p-4">{error}</p>}{!claim ? <p className="mt-8 mono">Reading canonical claim state…</p> : permitted ? <form onSubmit={submit} className="challenge-form mt-12 grid gap-5"><label>Reason<select name="reason"><option>wrong attribution</option><option>work after cutoff</option><option>duplicated contribution</option><option>out of scope</option><option>overstated impact</option></select></label><label>Counter-evidence URL<input name="url" placeholder="https://…"/></label><button disabled={!!stage} className="button coral w-fit disabled:opacity-50">Freeze challenge</button></form> : <p className="mt-10">The current canonical claim state does not permit a new challenge.</p>}<TxLifecycle stage={stage}/><Link className="mt-8 inline-block underline" href={`/claim/${id}`}>Return to dossier</Link></div>;
}
